### ISSUE TITLE
[ISSUE] 404

### ISSUE THREAD

**Issue by mrepol742** [abass-dev/portfolio#3]
![image](https://user-images.githubusercontent.com/62317165/155192110-32ebe3a4-8879-403f-9657-ad35439d8090.png)
It doesnt get deployed to the github pages environment tho u can deploy like this one **https://gitname.github.io/react-gh-pages**
heres the repo: https://github.com/gitname/react-gh-pages

**Comment by abass-dev** [comment]
you have the wrong address 
Check here https://abass-dev.github.io/
